NDefines.NGame.START_DATE = "1444.11.11"
NDefines.NGame.END_DATE = "1871.5.11"
NDefines.NGame.MAX_RANDOM_NEW_WORLD = "1000.1.1"
NDefines.NGame.GREAT_POWER_FRENZY_START = "1750.1.1"

NDefines.NDiplomacy.DAYS_TO_DECLARE_WAR = 1     --30→1
NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 150
NDefines.NDiplomacy.SPY_NETWORK_DISTANCE_EFFECT = 0.1
NDefines.NDiplomacy.IMPERIAL_CITY_IA = 0.0015
NDefines.NDiplomacy.MAX_FREE_CITIES = 45
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 180
NDefines.NDiplomacy.HRE_FOREIGN_CONTROL_PENALTY = -0.002
NDefines.NDiplomacy.REQUEST_HEIR_AE = 5
NDefines.NDiplomacy.WARNING_YEARS = 10
NDefines.NDiplomacy.FABRICATE_CLAIM_COST = 16
NDefines.NDiplomacy.AE_HRE_INTERNAL = 0.25
NDefines.NDiplomacy.PEACE_COST_DEMAND_PROVINCE = 1.0                --0.8→1.0
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0.1	    --0.33→-0.10    -- How much each great project multiplies a war score cost by (so 1 GP adds 33% 2 add 66% etc)
NDefines.NDiplomacy.PO_DEMAND_PROVINCES_AE = 0.40                   --0.6→0.40
NDefines.NDiplomacy.PO_BECOME_VASSAL_AE = 0.30                      --0.4→0.30
NDefines.NDiplomacy.PO_TRANSFER_VASSAL_AE = 0.30                    --0.4→0.30
NDefines.NDiplomacy.PO_FORCE_JOIN_EMPIRE_AE = 0                     --0.20→0
NDefines.NDiplomacy.PO_RETURN_CORES_AE = 0.20                       --0.4→0.20
NDefines.NDiplomacy.DIPLOMAT_SPEED = 40.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.05
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.15
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 70
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 70
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 70
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 1.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -10.0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 1.0
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12	                        --60→12
NDefines.NDiplomacy.CRUSADE_TIMEOUT_YEARS = 10 		            --30→10			-- Crusade timeout (years)

--dev half reduction	NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 200                        --100→200
--dev half reduction	NDefines.NDiplomacy.MARCH_BASE_DEVELOPMENT_CAP = 400                            --200→500
NDefines.NDiplomacy.PO_DEMAND_PROVINCES_AE = 0.4                                --0.6→0.4
--dev half reduction	NDefines.NDiplomacy.PO_RETURN_CORES_AE = 0.2                                    --0.4→0.2
--dev half reduction	NDefines.NDiplomacy.PO_FORM_PU_AE = 0.10                                        --0.2→0.1
--dev half reduction	NDefines.NDiplomacy.PO_CONCEDE_COLONIAL_AE = 0.1                                --0.2→0.1
--dev half reduction	NDefines.NDiplomacy.PO_BECOME_VASSAL_AE = 0.25                                  --0.5→0.25
--dev half reduction	NDefines.NDiplomacy.PO_FORCE_JOIN_EMPIRE_AE = 0.1                               --0.2→0.1
--dev half reduction	NDefines.NDiplomacy.PO_TRANSFER_VASSAL_AE = 0.15                                --0.3→0.15
--dev half reduction	NDefines.NDiplomacy.PEACE_COST_DEMAND_PROVINCE = 0.4                                                --0.8→0.4
--dev half reduction	NDefines.NDiplomacy.PEACE_COST_CONCEDE_PROVINCE = 0.4                                               --0.8→0.4
--dev half reduction	NDefines.NDiplomacy.PEACE_COST_BECOME_VASSAL = 0.4                                                  --0.8→0.4
--dev half reduction	NDefines.NDiplomacy.PEACE_COST_RETURN_CORE = 0.4                                                    --0.8→0.4
--dev half reduction	NDefines.NDiplomacy.PEACE_COST_REVOKE_CORE = 0.2                                                    --0.4→0.2
--dev half reduction	NDefines.NDiplomacy.PEACE_COST_RELEASE_ANNEXED = 0.4                                                --0.8→0.4
--dev half reduction	NDefines.NDiplomacy.PEACE_COST_RELEASE_VASSAL = 0.2                                                 --0.4→0.2
--dev half reduction	NDefines.NDiplomacy.OVEREXTENSION_FACTOR = 0.4                                                      --0.8→0.4
--dev half reduction	NDefines.NDiplomacy.OVEREXTENSION_OVERSEAS_FACTOR = 0.25                                                 --0.50→0.25

NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0	--0.4→0-- Multiplier for morale damage taken by backrow
NDefines.NMilitary.BACK_LINE_REINFORCE_SPEED = 40 --2→40
NDefines.NMilitary.GARRISON_SIZE = 2000     --1000→2000-- GARRISON_SIZE
NDefines.NMilitary.SIEGE_FORCE_NEEDED_MULTIPLIER = 0.5  --3→0.5	-- x times garrison to be able to siege.
NDefines.NMilitary.SIEGE_GARRISON_SURRENDER = 500   --100→500-- A siege ends when there is less than 100 defenders left.
NDefines.NMilitary.COMBAT_DICE_SIDE = 6	--10→6
NDefines.NMilitary.INFANTRY_SPEED = 1.5             --2.0→1.5
NDefines.NMilitary.CAVALRY_SPEED = 2.0              --2.0→2.0
NDefines.NMilitary.ARTILLERY_SPEED = 1.0            --2.0→1.0
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40	--25→40
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 60	--40→60
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.666    --0.4→0.666 (5 years)
NDefines.NMilitary.NAVAL_BASE_DISENGAGEMENT_CHANCE = 0.20       --0.10→0.20			-- Chance of disengaging from naval battles every day when out of morale	0-1 range
NDefines.NMilitary.GALLEY_BONUS_INLAND_SEA = 2.0        --1.0→2.0
NDefines.NMilitary.GALLEY_BONUS_COASTAL_SEA = 0       --0.50→0
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 1    --10→1
NDefines.NMilitary.FORTRESS_COST = 0.25                             --  0.50→0.25
NDefines.NMilitary.COAST_RAID_RANGE = 3 --6→3
NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.05
NDefines.NMilitary.SUPPLYLIMIT_BASE_MULTIPLIER = 3.0
NDefines.NMilitary.BATTLE_DAILY_MORALE_DAMAGE = 0       --0.01→0	-- Deployed troops take this fraction of their maximum morale as damage
NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.20		-- 250→200 men per manpower
NDefines.NMilitary.BATTLE_DAILY_MORALE_DAMAGE = 0       --0.01→0	-- Deployed troops take this fraction of their maximum morale as damage
NDefines.NMilitary.NAVAL_SUPPLY_RANGE = 300             --150→300 						-- Supply range for ships.

NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 20.0	--50→20
NDefines.NGovernment.CENTRALIZE_STATE_ADM_COST = 100	--50→100

--dev half reduction	NDefines.NCountry.CORRUPTION_COST = 0.025                                      --0.05→0.025
--dev half reduction	NDefines.NCountry.PS_MAKE_PROVINCE_CORE = 5                                    --10→5
NDefines.NCountry.SHOGUN_INTERACTIONS_LEGITIMACY = 0
NDefines.NCountry.CULTURAL_UNION_MIN_DEV = 2000
NDefines.NCountry.CULTURAL_UNION_MIN_RANK = 6
NDefines.NCountry.MIN_DEV_FOR_FREE_CITY = 3
NDefines.NCountry.HRE_RANK = 6
NDefines.NCountry.HRE_MAX_RANK = 4
NDefines.NCountry.HRE_MAX_RANK_ELECTOR = 5
NDefines.NCountry.HRE_INCIDENT_MEMBER_SUPPORT_IA = 0.02
NDefines.NCountry.SUBJECT_MAX_RANK = 3
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_2 = 5
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_3 = 10
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_2 = 10
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_3 = 25
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 100
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 250
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_X = 50
NDefines.NCountry.ADDITIONAL_MIN_DEVELOPMENT_FOR_GOV_RANK_X = 250
NDefines.NCountry.MAX_GOV_RANK = 6
NDefines.NCountry.EXPLORE_COAST_EVENT_CHANCE = 0
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_1 = 3004
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_2 = 3005
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_3 = 3006
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_4 = 3007
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_5 = 3008
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_6 = 3009
NDefines.NCountry.MIN_DEV_FOR_OLD_GREAT_POWER = 300
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 2
NDefines.NCountry.MERCHANT_REPUBLIC_SIZE_LIMIT = 75
NDefines.NCountry.PS_BUY_CONQUISTADOR = 2000
NDefines.NCountry.PS_BUY_EXPLORER = 2000
NDefines.NCountry.OVERSEAS_DISTANCE = 600
NDefines.NCountry.REVOLUTION_SPREAD_COUNT = 10
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -10                                   -- -50→-10
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25                                 -- -50→-25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -50                           --0→-50
NDefines.NCountry.NEW_HEIR_PRESTIGE_HIT = -10                                   -- -20→-10
NDefines.NCountry.NEW_HEIR_PRESTIGE_THRESHOLD = -50                             --0→-50
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0                        -- -25.0→0
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0                                        -- -10.0→0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0                                     -- -10.0→0
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 2.0                 --4.0→2.0
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 1.0                        --2.0→1.0
NDefines.NCountry.STRENGTHEN_GOVERNMENT_LEGITIMACY = 20                         --10→20
NDefines.NCountry.MAX_ACTIVE_POLICIES = 10                                      --5→10		   	-- how many active policies at once.
NDefines.NCountry.MINIMUM_POLICY_TIME = 1       						        --10→1           -- how many years minimum for a policy
--dev half reduction	NDefines.NCountry.EXPAND_INFRASTRUCTURE_DEV_LIMIT = 20                          --15→20
--dev half reduction	NDefines.NCountry.STATE_MAINTENANCE_DEV_FACTOR = 0.004                          --0.007→0.003
--dev half reduction	NDefines.NCountry.REVOLT_SIZE_DEVELOPMENT_MULTIPLIER= 0.05                      --0.1→0.01
--dev half reduction	NDefines.NCountry.MISSIONARY_MAINTENANCE_DEVELOPMENT_FACTOR = 0.25              --0.5→0.25
--dev half reduction	NDefines.NCountry.DEVELOPMENT_FOR_BLOCKADE_COST = 0.25                          --0.5→0.25
--dev half reduction	NDefines.NCountry.DEVASTATION_DEVELOPMENT_SCALE = 2.5                           --5→2.5

NDefines.NEconomy.MERCHANT_TIME_DISTANCE = 0.15
NDefines.NEconomy.MISSIONARY_TIME_DISTANCE = 0.1
NDefines.NEconomy.CARAVAN_FACTOR = 20						--3→20	-- Development is divided by this factor, do not set to zero!
NDefines.NEconomy.CARAVAN_POWER_MIN = 0						--2→0
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 10              --5→10

NDefines.NAI.DIPLOMATIC_INTEREST_DISTANCE = 750
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 400
NDefines.NAI.PURSUE_DISTANCE = 400
NDefines.NAI.DIPLOMATIC_ACTION_WARNING_MAX_DISTANCE = 10
NDefines.NAI.DIPLOMATIC_ACTION_CLAIM_THRONE_MAX_DISTANCE = 500
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_HRE_FACTOR = 1.0
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_HRE_EMPEROR_FACTOR = 0.75
NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MIN_MONTHS = 1          -- 12   -- Número mínimo de meses para declarar rendicion incondicional
NDefines.NAI.DEVELOPMENT_CAP_BASE = 30	    --10→30     -- AI will not develop provinces that have more development than this or DEVELOPMENT_CAP_MULT*original development (whichever is bigger)
NDefines.NAI.DEVELOPMENT_CAP_MULT = 3       --2→3
NDefines.NAI.PEACE_TIME_MONTHS = 12                                 -- 60  -- Tiempo de "AI stubbornness in a war", un modificador de aceptar la paz

NDefines.NGraphics.MIN_PROVINCES_FOR_NAME_ON_MAP = 1
NDefines.NGraphics.MIN_PROVINCES_FOR_REGION = 10
NDefines.NGraphics.MAX_TRADE_NODE_FLAGS_SHOWN = 8
NDefines.NGraphics.WATER_MAP_MODE_COLOR_R = 0.20
NDefines.NGraphics.WATER_MAP_MODE_COLOR_G = 0.29
NDefines.NGraphics.WATER_MAP_MODE_COLOR_B = 0.50
NDefines.NReligion.MAYA_COLLAPSE_PROVINCES = 2
NDefines.NGraphics.EQUATOR_COORDINATE_Y = 200

NDefines.NFrontend.FRONTEND_POS_X = 3850.0
NDefines.NFrontend.FRONTEND_POS_Y = 1900.0
NDefines.NFrontend.FRONTEND_LOOK_X = 3850.0
NDefines.NFrontend.FRONTEND_LOOK_Z = 1150.0
NDefines.NFrontend.SETTINGS_LOOK_X = 2958.0
NDefines.NFrontend.TUTORIAL_LOOK_X = 2894.0
NDefines.NFrontend.CREDITS_LOOK_X = 3077.0


NDefines.NFrontend.CAMERA_LOOKAT_X = 2800.0
NDefines.NFrontend.CAMERA_LOOKAT_Z = 1050.0
NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_X = 2800.0
NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_Z = 1050.0
NDefines.NFrontend.CAMERA_START_X = 2800.0
NDefines.NFrontend.CAMERA_START_Y = 1300.0
NDefines.NFrontend.CAMERA_START_Z = 750.0
NDefines.NFrontend.CAMERA_END_X = 2800.0
NDefines.NFrontend.CAMERA_END_Y = 2300.0
NDefines.NFrontend.CAMERA_END_Z = 1000.0
NDefines.NFrontend.FRONTEND_POS_Z = 1050.0
NDefines.NFrontend.SETTINGS_POS_X = 2800.0
NDefines.NFrontend.SETTINGS_POS_Y = 2700.0
NDefines.NFrontend.SETTINGS_POS_Z = 1050.0
NDefines.NFrontend.SETTINGS_LOOK_Z = 1050.0
NDefines.NFrontend.MP_OPTIONS_POS_X = 2800.0
NDefines.NFrontend.MP_OPTIONS_POS_Y = 2700.0
NDefines.NFrontend.MP_OPTIONS_POS_Z = 1050.0
NDefines.NFrontend.MP_OPTIONS_LOOK_X = 2800.0
NDefines.NFrontend.MP_OPTIONS_LOOK_Z = 1050.0
NDefines.NFrontend.TUTORIAL_POS_X = 2800.0
NDefines.NFrontend.TUTORIAL_POS_Y = 2700.0
NDefines.NFrontend.TUTORIAL_POS_Z = 1050.0
NDefines.NFrontend.TUTORIAL_LOOK_Z = 1050.0
NDefines.NFrontend.CONTENT_POS_X = 2800.0
NDefines.NFrontend.CONTENT_POS_Y = 2700.0
NDefines.NFrontend.CONTENT_POS_Z = 1050.0
NDefines.NFrontend.CONTENT_LOOK_X = 2800.0
NDefines.NFrontend.CONTENT_LOOK_Z = 1050.0
NDefines.NFrontend.CREDITS_POS_X = 2800.0
NDefines.NFrontend.CREDITS_POS_Y = 2700.0
NDefines.NFrontend.CREDITS_POS_Z = 1050.0
NDefines.NFrontend.CREDITS_LOOK_Z = 1050.0

NDefines.NReligion.COUNCIL_BASE_COST = 10000
NDefines.NReligion.YEARLY_DOOM_INCREASE = 0.1
NDefines.NReligion.MAX_CHRISTIAN_RELIGIOUS_CENTERS = 8
NDefines.NReligion.MAX_RELIGIOUS_CENTER_SPREAD_DISTANCE = 250.0
NDefines.NReligion.REFORM_DESIRE_PER_YEAR = 0.001
NDefines.NReligion.PAPAL_TITHE_PERCENTAGE = 0.03
NDefines.NReligion.MIN_CARDINALS = 14
NDefines.NReligion.MAX_CARDINALS = 98
NDefines.NReligion.MAX_CARDINALS_PER_COUNTRY = 10
NDefines.NReligion.PICK_GOLDEN_BULL_COST = 4000
MINIMUM_DEVELOPMENT_ALLOWED = 10.0

NDefines.NNationDesigner.POINTS_AVAILABLE = 500
NDefines.NNationDesigner.MEMBER_OF_HRE_COST = 5
NDefines.NNationDesigner.MEMBER_OF_HRE_PROVINCE_COST = 0.05
NDefines.NNationDesigner.MEMBER_OF_HRE_COST = 0
NDefines.NNationDesigner.MEMBER_OF_HRE_PROVINCE_COST = 0.0
NDefines.NNationDesigner.MAX_DISTANCE_TO_OWNER_AREA = 800
NDefines.NNationDesigner.MAX_GOVERNMENT_RANK = 6
NDefines.NNationDesigner.MANDATE_SUBCONTINENT_NAME = "ruthenia_superregion"

-- For Ideas Expanded

NDefines.NCountry.PS_BUY_IDEA = 300
NDefines.NCountry.FREE_IDEA_GROUP_COST  = 5 -- This amount of ideas needed for a national idea to unlock
NDefines.NCountry.IDEA_TO_TECH = -0.01
NDefines.NCountry.MAX_ACTIVE_POLICIES = 12
NDefines.NCountry.BASE_POSSIBLE_POLICIES = 4
NDefines.NCountry.MINIMUM_POLICY_TIME = 2
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.35 --35

-- Innovativeness
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 1 -- 2.0
NDefines.NCountry.INNOVATIVENESS_DAYS_AFTER_FIRST_PICK_VIABLE = 60 --90
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 2 -- 4.0